# Generated by Django 4.1.1 on 2023-04-01 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('r_account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='update_at',
        ),
    ]
