# Generated by Django 4.1.1 on 2023-03-30 09:43

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drift', models.CharField(choices=[('ustoz', 'Ustoz kerak'), ('shogird', 'Shogird kerak'), ('hodim', 'Hodim kerak'), ('ish_joyi', 'Ish joyi kerak'), ('sherig', 'Sherig kerak')], max_length=100)),
                ('name', models.CharField(max_length=130, verbose_name='Ism familyangiz')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True)),
                ('age', models.PositiveIntegerField(verbose_name='Yoshingiz')),
                ('address', models.CharField(max_length=300, verbose_name='Manzilingiz')),
                ('technology', models.CharField(help_text='..larni bilaman', max_length=500, verbose_name='Texnologiya, men')),
                ('jobs', models.CharField(max_length=300, verbose_name='Kasp')),
                ('price', models.CharField(max_length=100, verbose_name='Talab qilinadigan summa')),
                ('application_time', models.CharField(max_length=51, verbose_name='Murojat qilish vaqti')),
                ('phone', models.CharField(max_length=120, verbose_name="Bog'lanish uchun tel nomer")),
                ('photo', models.ImageField(blank=True, default='default/ustoz_shogird.jpg', null=True, upload_to='photo/%Y/%m/')),
                ('title', models.TextField(verbose_name="Qo'shimcha malumot")),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=41)),
                ('body', models.CharField(max_length=310, verbose_name='Comment qoldiring')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='post.post')),
            ],
        ),
    ]
